from typing import Dict, Any

def format_discord_embed(signal: Dict[str, Any]) -> str:
    """Build rich Discord embed per blueprint format."""
    pair = signal['pair']
    direction = signal['direction']
    tf = signal['timeframe']
    
    entry = signal['entry']
    stop = signal['stop']
    target = signal['target']
    rr = signal.get('rr_ratio', 2.0)
    
    confidence = signal.get('confidence_score', signal.get('confidence', 7.0))
    strategies = ', '.join(signal.get('strategies', ['Multi']))
    
    embed = f"""
🔔 **{pair} {direction} {tf.upper()}**
══════════════════════════════

**📍 Entry Zone**: `{entry:.2f}`
**🛑 Stop Loss**: `{stop:.2f}` (ATR-based)
**🎯 TP1**: `{target:.2f}`

**⚖️ Risk:Reward**: `1:{rr:.1f}`
**📊 Confidence**: `{confidence:.1f}/10`
**⚡ Strategies**: {strategies}

**Regime**: Trending | Volatility: Normal
**Edge**: Multi-confluence signal
══════════════════════════════
*Generated by Super Joint Engine*
"""
    return embed
